# Generated by Django 5.2.13 on 2026-04-29 17:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legaldocument',
            name='text',
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='content',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
