# Generated by Django 5.2.13 on 2026-04-29 17:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_remove_legaldocument_text_legaldocument_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legaldocument',
            old_name='content',
            new_name='content_ar',
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='content_en',
            field=ckeditor.fields.RichTextField(default='test'),
            preserve_default=False,
        ),
    ]
