# Generated by Django 5.2.13 on 2026-04-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('privacy', 'Privacy Terms'), ('conditions', 'Terms and Conditions')], max_length=15)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
