# Generated by Django 5.2.13 on 2026-04-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegalDocument',
        ),
    ]
