# Generated by Django 5.2.13 on 2026-04-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branding', '0002_delete_legaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(max_length=20)),
                ('secondary_color', models.CharField(max_length=20)),
                ('font_color', models.CharField(max_length=20)),
                ('font_color_secondary', models.CharField(max_length=20)),
            ],
        ),
    ]
